export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  ENTERPRISE_NOT_CERTIFIED: 'ENTERPRISE_NOT_CERTIFIED',
  ENTERPRISE_CERTIFICATION_PENDING: 'ENTERPRISE_CERTIFICATION_PENDING',
  DEPOSIT_NOT_APPROVED: 'DEPOSIT_NOT_APPROVED',
  BLACKLISTED: 'BLACKLISTED',
  AUCTION_ENDED: 'AUCTION_ENDED',
  INVALID_BID_INCREMENT: 'INVALID_BID_INCREMENT',
  FILE_FORBIDDEN: 'FILE_FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
