import {
  NotificationChannel,
  NotificationSendStatus,
  NotificationType,
} from '@prisma/client';
import { Test } from '@nestjs/testing';

import { NotificationsController } from '../../src/modules/notifications/notifications.controller';
import { NotificationsModule } from '../../src/modules/notifications/notifications.module';
import { NotificationsService } from '../../src/modules/notifications/notifications.service';
import { PrismaService } from '../../src/prisma/prisma.service';

type NotificationRecord = {
  id: string;
  type: NotificationType;
  channel: NotificationChannel;
  receiverEnterpriseId: string;
  lotId: string | null;
  lotTitle: string;
  content: string;
  sendStatus: NotificationSendStatus;
  sentAt: Date | null;
  readAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  receiverEnterprise: {
    id: string;
    name: string;
  };
  lot: {
    id: string;
    title: string;
  } | null;
};

function createNotification(
  overrides: Partial<NotificationRecord> = {},
): NotificationRecord {
  const now = new Date('2026-05-17T10:00:00.000Z');

  return {
    id: 'notification-1',
    type: NotificationType.WIN,
    channel: NotificationChannel.IN_APP,
    receiverEnterpriseId: 'enterprise-1',
    lotId: 'lot-1',
    lotTitle: '铜精矿竞拍',
    content: '您参与的铜精矿竞拍已结束，已中标，请办理签约与尾款手续。',
    sendStatus: NotificationSendStatus.PENDING,
    sentAt: null,
    readAt: null,
    createdAt: now,
    updatedAt: now,
    receiverEnterprise: {
      id: 'enterprise-1',
      name: '华宁铜业有限公司',
    },
    lot: {
      id: 'lot-1',
      title: '铜精矿竞拍',
    },
    ...overrides,
  };
}

function createPrismaMock(records: NotificationRecord[]) {
  const store = [...records];

  return {
    notification: {
      findMany: jest.fn(({ where, skip = 0, take = store.length }) => {
        const result = store.filter((item) => {
          if (where?.sendStatus && item.sendStatus !== where.sendStatus) {
            return false;
          }

          if (where?.type && item.type !== where.type) {
            return false;
          }

          return true;
        });

        return Promise.resolve(result.slice(skip, skip + take));
      }),
      count: jest.fn(({ where }) =>
        Promise.resolve(
          store.filter((item) => {
            if (where?.sendStatus && item.sendStatus !== where.sendStatus) {
              return false;
            }

            if (where?.type && item.type !== where.type) {
              return false;
            }

            return true;
          }).length,
        ),
      ),
    },
  };
}

describe('NotificationsService', () => {
  it('wires the notifications module controllers', async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [NotificationsModule],
    })
      .overrideProvider(PrismaService)
      .useValue(createPrismaMock([]))
      .compile();

    expect(moduleRef.get(NotificationsController)).toBeInstanceOf(
      NotificationsController,
    );
  });

  it('lists pending auction notifications generated by bidding core', async () => {
    const service = new NotificationsService(
      createPrismaMock([
        createNotification(),
        createNotification({
          id: 'sent',
          sendStatus: NotificationSendStatus.SENT,
        }),
      ]) as never,
    );

    const result = await service.list({
      page: 1,
      pageSize: 10,
      sendStatus: NotificationSendStatus.PENDING,
    });

    expect(result.items.map((item: { id: string }) => item.id)).toEqual([
      'notification-1',
    ]);
    expect(result.items[0]).toEqual(
      expect.objectContaining({
        receiverEnterpriseName: '华宁铜业有限公司',
        lotTitle: '铜精矿竞拍',
        typeCode: NotificationType.WIN,
        channelCode: NotificationChannel.IN_APP,
        sendStatusCode: NotificationSendStatus.PENDING,
      }),
    );
  });

  it('labels skipped sms records as not configured', async () => {
    const service = new NotificationsService(
      createPrismaMock([
        createNotification({
          channel: NotificationChannel.SMS,
          sendStatus: NotificationSendStatus.FAILED,
          content: '短信供应商未配置，未发送。您参与的铜精矿竞拍已结束。',
        }),
      ]) as never,
    );

    const result = await service.list({
      page: 1,
      pageSize: 10,
    });

    expect(result.items[0]).toEqual(
      expect.objectContaining({
        channelCode: NotificationChannel.SMS,
        sendStatus: '未配置',
        sendStatusCode: NotificationSendStatus.FAILED,
      }),
    );
  });
});
